import type { ProjectPagesConfig } from "./types";

type MessageValues = Record<string, string | number>;
type MessageCatalog = Record<string, string>;

const BUILTIN_MESSAGES: Record<string, Readonly<MessageCatalog>> = Object.freeze({
  en: Object.freeze({
    "skip.content": "Skip to content",
    "nav.project": "Project",
    "nav.overview": "Overview",
    "nav.stats": "Stats",
    "nav.evidence": "Evidence",
    "preferences.summary": "Preferences",
    "preferences.description": "Presentation preferences are shared across compatible project Pages on this origin.",
    "preferences.theme": "Theme",
    "preferences.theme.system": "System",
    "preferences.theme.light": "Light",
    "preferences.theme.dark": "Dark",
    "preferences.contrast": "Contrast",
    "preferences.contrast.system": "System",
    "preferences.contrast.normal": "Normal",
    "preferences.contrast.high": "High",
    "preferences.contrast.low": "Low",
    "preferences.language": "Language",
    "preferences.reset": "Use project defaults",
    "footer.evidence": "Evidence is observational and revision-bound; missing or malformed evidence is never treated as success.",
    "footer.repository": "Repository",
    "overview.evidenceTitle": "Measured project evidence",
    "overview.evidenceBody": "Stats and accomplishments are rendered from explicit evidence producers. The template does not reinterpret benchmark semantics or manufacture a synthetic quality score.",
    "overview.viewStats": "View stats",
    "overview.inspectEvidence": "Inspect evidence provenance",
    "stats.eyebrow": "Measured evidence",
    "stats.title": "Stats",
    "stats.intro": "Current measurements remain separate by producer and evidence family.",
    "stats.currentTitle": "Current measurements",
    "stats.loading": "Loading published evidence…",
    "stats.table.metric": "Metric",
    "stats.table.value": "Value",
    "stats.table.state": "State",
    "stats.table.source": "Source",
    "stats.chartsTitle": "Comparable measurements",
    "stats.chartsIntro": "Charts are shown only for source-produced numeric metrics that share a compatible unit. They do not create a combined quality score.",
    "stats.chart.current": "Current",
    "stats.chart.baseline": "Baseline",
    "stats.accomplishmentsTitle": "Accomplishments",
    "stats.noAccomplishments": "No published accomplishment evidence is available for this revision.",
    "stats.recordedAccomplishment": "Recorded accomplishment",
    "evidence.eyebrow": "Provenance",
    "evidence.title": "Evidence",
    "evidence.intro": "Each source retains its producer, freshness, revision, and retrieval state.",
    "evidence.loading": "Loading evidence sources…",
    "evidence.table.source": "Source",
    "evidence.table.repository": "Repository",
    "evidence.table.producer": "Producer",
    "evidence.table.state": "State",
    "evidence.table.generated": "Generated",
    "evidence.table.evidenceRevision": "Evidence revision",
    "evidence.table.currentRevision": "Current revision",
    "evidence.table.diagnostic": "Diagnostic",
    "common.unavailable": "Unavailable",
    "common.unknown": "Unknown",
    "common.unnamedMetric": "Unnamed metric",
    "common.baseline": "baseline {value}",
    "coding.checklist": "Checklist work",
    "coding.checklistValue": "{remaining} remaining · {completed}/{total} complete",
    "coding.publicContracts": "Public contracts verified",
    "coding.httpEndpoints": "HTTP endpoints verified",
    "coding.functionsCovered": "Functions covered by tests",
    "coding.linesCovered": "Lines covered by tests",
    "coding.verificationPassed": "Verification checks passed",
    "coding.actionableFindings": "Actionable findings",
    "coding.findingsValue": "{total} total · {highPriority} high priority",
    "coding.discoveredZero": "0 discovered",
    "stats.status.oneSource": "{measurements} measurements from 1 configured evidence source.",
    "stats.status.manySources": "{measurements} measurements from {sources} configured evidence sources.",
    "evidence.status.attention": "{attention} of {total} evidence sources need attention; unavailable, malformed, mismatched, or stale evidence is not treated as green.",
    "evidence.status.currentOne": "1 evidence source loaded with current identity and revision.",
    "evidence.status.currentMany": "{total} evidence sources loaded with current identity and revision.",
    "evidence.inspectDiagnostics": "{state}; inspect {source} evidence diagnostics",
  }),
  de: Object.freeze({
    "skip.content": "Zum Inhalt springen",
    "nav.project": "Projekt",
    "nav.overview": "Übersicht",
    "nav.stats": "Statistiken",
    "nav.evidence": "Nachweise",
    "preferences.summary": "Einstellungen",
    "preferences.description": "Darstellungseinstellungen werden zwischen kompatiblen Projektseiten auf diesem Ursprung geteilt.",
    "preferences.theme": "Farbschema",
    "preferences.theme.system": "System",
    "preferences.theme.light": "Hell",
    "preferences.theme.dark": "Dunkel",
    "preferences.contrast": "Kontrast",
    "preferences.contrast.system": "System",
    "preferences.contrast.normal": "Normal",
    "preferences.contrast.high": "Hoch",
    "preferences.contrast.low": "Niedrig",
    "preferences.language": "Sprache",
    "preferences.reset": "Projektstandard verwenden",
    "footer.evidence": "Nachweise sind beobachtungs- und revisionsgebunden; fehlende oder fehlerhafte Nachweise gelten nie als Erfolg.",
    "footer.repository": "Repository",
    "overview.evidenceTitle": "Gemessene Projektnachweise",
    "overview.evidenceBody": "Statistiken und erreichte Ergebnisse werden aus expliziten Nachweisquellen dargestellt. Die Vorlage interpretiert Benchmark-Semantik nicht neu und erzeugt keinen synthetischen Qualitätsscore.",
    "overview.viewStats": "Statistiken ansehen",
    "overview.inspectEvidence": "Nachweisprovenienz prüfen",
    "stats.eyebrow": "Gemessene Nachweise",
    "stats.title": "Statistiken",
    "stats.intro": "Aktuelle Messwerte bleiben nach Produzent und Nachweisfamilie getrennt.",
    "stats.currentTitle": "Aktuelle Messwerte",
    "stats.loading": "Veröffentlichte Nachweise werden geladen…",
    "stats.table.metric": "Metrik",
    "stats.table.value": "Wert",
    "stats.table.state": "Status",
    "stats.table.source": "Quelle",
    "stats.chartsTitle": "Vergleichbare Messwerte",
    "stats.chartsIntro": "Diagramme werden nur für von einer Quelle erzeugte numerische Metriken mit kompatibler Einheit angezeigt. Sie erzeugen keinen zusammengefassten Qualitätsscore.",
    "stats.chart.current": "Aktuell",
    "stats.chart.baseline": "Basiswert",
    "stats.accomplishmentsTitle": "Erreichte Ergebnisse",
    "stats.noAccomplishments": "Für diese Revision sind keine veröffentlichten Nachweise zu erreichten Ergebnissen verfügbar.",
    "stats.recordedAccomplishment": "Erfasstes Ergebnis",
    "evidence.eyebrow": "Provenienz",
    "evidence.title": "Nachweise",
    "evidence.intro": "Jede Quelle behält Produzent, Aktualität, Revision und Abrufstatus bei.",
    "evidence.loading": "Nachweisquellen werden geladen…",
    "evidence.table.source": "Quelle",
    "evidence.table.repository": "Repository",
    "evidence.table.producer": "Produzent",
    "evidence.table.state": "Status",
    "evidence.table.generated": "Erzeugt",
    "evidence.table.evidenceRevision": "Nachweisrevision",
    "evidence.table.currentRevision": "Aktuelle Revision",
    "evidence.table.diagnostic": "Diagnose",
    "common.unavailable": "Nicht verfügbar",
    "common.unknown": "Unbekannt",
    "common.unnamedMetric": "Unbenannte Metrik",
    "common.baseline": "Basiswert {value}",
    "coding.checklist": "Checklistenarbeit",
    "coding.checklistValue": "{remaining} offen · {completed}/{total} abgeschlossen",
    "coding.publicContracts": "Öffentliche Verträge verifiziert",
    "coding.httpEndpoints": "HTTP-Endpunkte verifiziert",
    "coding.functionsCovered": "Durch Tests abgedeckte Funktionen",
    "coding.linesCovered": "Durch Tests abgedeckte Zeilen",
    "coding.verificationPassed": "Bestandene Verifikationsprüfungen",
    "coding.actionableFindings": "Bearbeitbare Befunde",
    "coding.findingsValue": "{total} insgesamt · {highPriority} hohe Priorität",
    "coding.discoveredZero": "0 gefunden",
    "stats.status.oneSource": "{measurements} Messwerte aus 1 konfigurierten Nachweisquelle.",
    "stats.status.manySources": "{measurements} Messwerte aus {sources} konfigurierten Nachweisquellen.",
    "evidence.status.attention": "{attention} von {total} Nachweisquellen benötigen Aufmerksamkeit; nicht verfügbare, fehlerhafte, unpassende oder veraltete Nachweise werden nicht als grün behandelt.",
    "evidence.status.currentOne": "1 Nachweisquelle mit aktueller Identität und Revision geladen.",
    "evidence.status.currentMany": "{total} Nachweisquellen mit aktueller Identität und Revision geladen.",
    "evidence.inspectDiagnostics": "{state}; Nachweisdiagnose für {source} prüfen",
  }),
});

export function translate(
  config: ProjectPagesConfig,
  locale: string,
  key: string,
  values: MessageValues = {},
) {
  const configured = config.preferences?.messages?.[locale]?.[key];
  const template =
    (typeof configured === "string" && configured) ||
    BUILTIN_MESSAGES[locale]?.[key] ||
    BUILTIN_MESSAGES.en[key] ||
    key;

  return template.replace(/\{([A-Za-z0-9_]+)\}/g, (_match, name: string) =>
    name in values ? String(values[name]) : `{${name}}`,
  );
}

export function applyTranslations(
  documentObject: Document | null | undefined,
  config: ProjectPagesConfig,
  locale: string,
) {
  if (!documentObject) return;
  for (const node of documentObject.querySelectorAll<HTMLElement>("[data-i18n]")) {
    const key = node.dataset.i18n;
    if (key) node.textContent = translate(config, locale, key);
  }
  for (const node of documentObject.querySelectorAll<HTMLElement>("[data-i18n-aria-label]")) {
    const key = node.dataset.i18nAriaLabel;
    if (key) node.setAttribute("aria-label", translate(config, locale, key));
  }
}
