name: Deploy Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  packages: read
  pages: write
  id-token: write

jobs:
  deploy-pages:
    name: Deploy Pages
    uses: moritzbrantner/reusable-workflows/.github/workflows/deploy-pages.yml@06942ee3031da5d7ec311ed1494c1b4dd80cec06
    with:
      node_version: "24"
      bun_version: ""
      install_command: ""
      build_command: "node ./bin/github-pages-template.mjs build --config ./site/pages.config.json --out ./dist"
      artifact_path: dist
      enable_pages: true
      cache_bun: false
      cache_node: false
